# Generated by Django 5.1.7 on 2025-04-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_rating_booking_review_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingspace',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
