# Generated by Django 5.1.7 on 2025-03-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coworkingspace_space_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coworkingspace',
            name='image_url',
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coworking_images/'),
        ),
    ]
