# Generated by Django 5.1.7 on 2025-03-27 07:10

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_coworkingspace_image_url_coworkingspace_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworkingspace',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='coworking_images/'),
        ),
    ]
