# Generated by Django 5.1.7 on 2025-04-01 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metropole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'metropoles',
            },
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='metropole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='core.metropole'),
        ),
    ]
